### ISSUE TITLE
Prima Issue

### ISSUE THREAD

**Issue by cioculo** [cioculo/hello-world#5]
fai qualcosa che te lo contesto

**Comment by oneonzero** [comment]
faccio io le modifiche ok ?

**Comment by cioculo** [comment]
ottimo vai pure

**Comment by cioculo** [comment]
> ottimo vai pure

**Comment by cioculo** [comment]
mi ero sbagliato

**Comment by oneonzero** [comment]
> 
> 
> mi ero sbagliato

procedo

**Comment by oneonzero** [comment]
ho fatto la modifica
